<a href="https://colab.research.google.com/github/financieras/AdventOfCode2021/blob/master/retos_solucion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 1
## Divisores de una serie de números
* Calcular todos los divisores de una serie de números.
* El usuario elige el rango de números, indicando el inicio y el final del rango.
 - Por ejemplo, entre 100 y 110
 * El programa muestra, junto a cada número del rango, todos los divisores que tiene cada uno de esos números.
  - Por ejemplo:
   - 100 -> [1,2,4,5,10,20,25,50,100]
   - 101 -> [1,101]
   - 102 -> [1,2,3,6,17,34,51,102]
   - 103 -> [1,103]
   - 104 -> [1,2,4,8,13,26,52,104]
   - 105 -> [1,3,5,7,15,21,35,105]
   - 106 -> [1,2,53,106]
   - 107 -> [1,107]
   - 108 -> [1,2,3,4,6,9,12,18,27,36,54,108]
   - 109 -> [1,109]
   - 110 -> [1,2,5,10,11,22,55,110]

In [ ]:
# Divisores de una serie de números
ini = int(input("Inicio: "))
fin = int(input("Final: "))
for n in range(ini, fin+1):
  divisores = []
  for i in range(1, n+1):
    if not(n % i):
      divisores.append(i)
  print(f"{n} -> {divisores}")

100 -> [1, 2, 4, 5, 10, 20, 25, 50, 100]
101 -> [1, 101]
102 -> [1, 2, 3, 6, 17, 34, 51, 102]
103 -> [1, 103]
104 -> [1, 2, 4, 8, 13, 26, 52, 104]
105 -> [1, 3, 5, 7, 15, 21, 35, 105]
106 -> [1, 2, 53, 106]
107 -> [1, 107]
108 -> [1, 2, 3, 4, 6, 9, 12, 18, 27, 36, 54, 108]
109 -> [1, 109]
110 -> [1, 2, 5, 10, 11, 22, 55, 110]


# Day 2
## Frecuencia de caracterers de un libro
* Analizar la frecuencia de todos los caracteres que contiene un libro
* El libro es: 
 - Frankenstein; Or, The Modern Prometheus by Mary Wollstonecraft Shelley
* Se puede obtener libremente del proyecto Gutemberg en esta dirección:
  - [Frankenstein](https://www.gutenberg.org/ebooks/84)

# Day 3
## Detectar el número diferente
* Generar un array de números enteros con una longitud aleatoria entre 3 y 15
* Los números del array son aleatorios enteros entre entre -99 y +99
* Los números del array serán todos pares, menos uno de ellos que será impar, o bien
* todos serán impares, menos uno de ellos que será par
* Mostrar en pantalla el array
* El objetivo es detectar el número que es diferente dentro del array
* Crear un método o función a la que pasamos como parámetro el array generado
* La función retorna ese número diferente que se ha de imprimir por pantalla

**Ejemplos**
 * [2, 4, 0, 100, 4, 11, 2602, 36]
  - Debería retornar: 11 (ya que es el único número impar del array)
 * [160, 3, 1719, 19, 11, 13, -21]
  - Debería retornar: 160 (ya que es el único número par del array)

In [ ]:
# Detectar el número diferente
import random
random.seed()

def genera():
  n = random.randint(3,15) # longitud que tendrá el array
  if random.random()<.5:   # tiramos una moneda a cara o cruz
    array = random.choices(range(-99, 100, 2), k=n-1)     # los n-1 impares
    array.append(random.choice(range(-98, 100, 2)))       # un par
  else:
    array = random.choices(range(-98, 100, 2), k=n-1)     # los n-1 pares
    array.append(random.choice(range(-99, 100, 2)))       # un impar
  random.shuffle(array)  # desordenamos el array para que el nº distinto no esté siempre el último
  return array

def encuentra_el_diferente(array):
  lista = []  # será una lista de casi todos 0 menos un 1, o al contrario
  for num in array:
    lista.append(num%2) # num%2 da 0 si PAR, da 1 si IMPAR
  if sum(lista) == 1: # en este caso en la lista solo hay un impar
    return f"Casi todos pares, el único impar es {array[lista.index(1)]}."
  else:
    return f"Casi todos impares, el único par es {array[lista.index(0)]}."

if __name__ == "__main__":
  array = genera()
  print(array)
  print(encuentra_el_diferente(array))

[81, -95, 19, -55, 91, 59, -76, 29, -75, 45, 71, 87, -85, 1, -51]
Casi todos impares, el único par es -76.


# Day 4
## Suma de números impares de un triángulo
Dado un triángulo de números impares como este:  
 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 1  
 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 3 &nbsp; &nbsp; &nbsp; &nbsp;5  
 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 7 &nbsp; &nbsp; &nbsp; &nbsp; 9 &nbsp; &nbsp; &nbsp; 11  
 &nbsp; &nbsp; 13 &nbsp; &nbsp; &nbsp; 15 &nbsp; &nbsp; &nbsp; &nbsp;  17 &nbsp; &nbsp; &nbsp; 19  
21 &nbsp; &nbsp; &nbsp; 23 &nbsp; &nbsp; &nbsp; 25 &nbsp; &nbsp; &nbsp; 27 &nbsp; &nbsp; &nbsp; 29  
... ... ... ... ... ... ... ... ... ... ... ... ...  

* Calcule la suma de los números en la enésima fila de este triángulo (comenzando en el índice 1)
* El programa genera aleatoriamente la fila y se la pasa como parámetro a una función que es la que da el resultado
* por ejemplo: 
 - Entrada -> Salida
 - 1ª fila -> 1
 - 2ª fila -> 3 + 5 = 8
 - 3ª fila -> 7 + 9 + 11 = 27

# Day 5
## Distribuir texto en líneas
* Crear una función que reciba como parámetros dos argumentos:
 - un string, por ejemplo frase = "ABCDEFGHIJKLIMNOQRSTUVWXYZ"
 - un número entero entre 1 y la longitud de la frase, por ejemplo, n= 4
* La función retornará un texto, que habitualmente ocupará varias líneas, donde en cada línea se pondrán n caracteres.
 - en la primera línea irán los n primeros caracteres
 - en la segunda línea los n siguientes caracteres
 - y asi sucesivamente hasta llegar a la última línea
 - en la última línea irán los caracteres necesarios para terminar de imprimir la frase
* Imprimir lo que retorna la función creada

**Ejemplo 1**
* Inputs:
 - frase = "ABCDEFGHIJKLIMNOQRSTUVWXYZ"
 - n = 4
* Output:  
 `ABCD`  
 `EFGH`  
 `IJKL`  
 `IMNO`  
 `QRST`  
 `UVWX`  
 `YZ`

**Ejemplo 2**
* Inputs:
 - frase = "ABCDEFG @HIJKLIMNOQRSTUVWXYZ"
 - n = 6
* Output:  
 `ABCDEF`  
 `G @HIJ`  
 `KLIMNO`  
 `QRSTUV`  
 `WXYZ`

# Day 6
## Matriz con escalones
* Dado el parámetro número de filas (n) crear una matriz:
 - El número de filas (n) puede variar entre 1 y 20
 - El número de columnas siempre es el triple que el de filas
 - La matriz está compuesta por ceros y unos según la distribución que se mustra en la imagen, según sea el valor del parámetro n.
* Se trata de imprimir la matriz en la terminal en función del valor de n que nos den.

![matriz.png](https://drive.google.com/uc?id=1yff9bW_yu-U1aTdbR2mTmWkD31ZPrqnc)

* Para n=5 se obtendría el siguente resultado:

![matriz.png](https://drive.google.com/uc?id=1Pz5wbwCls6DAwOh2SI0Nes-011nSLTjC)

# Day 7
## The Minion Game
* Kevin and Stuart want to play the 'The Minion Game'.

### Game Rules
* Both players are given the same string, s.
* Both players have to make substrings using the letters of the string s .
* Stuart has to make words starting with consonants.
* Kevin has to make words starting with vowels.
* The game ends when both players have made all possible substrings.

### Scoring
* A player gets +1 point for each occurrence of the substring in the string s.

#### For Example
* String s = BANANA
* Kevin's vowel beginning word = ANA
* Here, ANA occurs twice in BANANA. Hence, Kevin will get 2 Points.

* For better understanding, see the image below:

<img src="https://drive.google.com/uc?id=1ZlwIeyG_dsLQ04dQeKuNsGF9l6l5FDmi" alt="banana.png" width="420"/>

<img src="https://github.com/seldoncode/AdventOfCode2021/blob/main/Banana.png?raw=1" alt="Banana.png" width="420"/>


* Your **task** is to determine the winner of the game and their score.

### Function Description
* Complete the minion_game in the editor below.
* minion_game has the following parameters:
 - string string: the string to analyze

### Prints
* string: the winner's name and score, separated by a space on one line, or Draw if there is no winner

### Input Format
* A single line of input containing the string s.
* Note: The string  will contain only uppercase letters [A-Z].

### Constraints
* 0 < len(s) < 10**6

### Sample Input
BANANA

### Sample Output
Stuart 12

#### Note
* Vowels are only defined as A, E, I, O, U.

# Day 8
## List Comprehension
* Nos dan tres números enteros x, y, z que representan  dimensiones en 3D, junto con un número entero n.
* Tiene que imprimir una lista de todas las coordenadas posibles dadas por (i, j, k) en un espacio tridimensional donde la suma de i+j+k no es igual a n.
* Siendo:
 - 0 <= i <= x
 - 0 <= j <= y
 - 0 <= k <= z
* Formato de entrada:
 - Cuatro números enteros x, y, z, n en formato de tupla: (x,y,z,n)

### Restricciones
* Imprima la lista en orden lexicográfico creciente.

### Ejemplo 1
#### Entrada
 * (1,1,1,2)

#### Salida
* [[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1 , 1, 1]]

### Ejemplo 2
#### Entrada
 * (1,1,2,3)

#### Salida
* [[0,0,0], [0,0,1], [0,0,2], [0,1,0], [0,1,1], [1,0,0], [1,0,1], [1,1,0], [1,1,2]]

### Nota
* Realizar el código utilizando una lista comprimida (List Comprehension)

# Day 9
## Generar matrices
* Generar una **matriz cuadrada** de n filas y n columnas, esto es, de dimensión n×n
* El valor de n puede variar entre 1 y 100
* Si n es uno, la matriz es de un elemento, por ejemplo, [[5]]
* Si n es dos la matriz es de dimensión 2×2, por ejemplo: [[1, 2], [0, -3]]
* Los elementos de la matriz tienen que ser números aleatorios entreros entre -9 y +9.
* La distribución de estos números debe seguir una distribución de probabilidad escalonada con las siguiente probabilidades: [25,20,16,12,9,7,5,3,2,1]
 - 25 indica que la probabilidad de que salga un 0 es del 25%
 - 20 indica que la probabilidad de que salga un 1 o -1 es del 20%
 - 16 indica que la probabilidad de que salga un 2 o -2 es del 16%
 - ... / ...
 - 1 indica que la probabilidad de que salga un 9 o -9 es del 1% 
* No puede existir ninguna fila o columna donde todos sus elementos sean cero.
* Dado n mostrar la matriz en pantalla

In [ ]:
import numpy as np
from random import random

def matriz(n):
  while True:
    m = [[-x if random()<.5 else x for x in np.random.choice(10, n, p=[.25,.20,.16,.12,.09,.07,.05,.03,.02,.01])] for _ in range(n)]
    m = np.asarray(m)
    if np.where(~m.any(axis=0))[0].size == 0 and np.where(~m.any(axis=1))[0].size == 0:
      break
  return m

print(matriz(10))

[[ 3  4  0  3 -1 -1  1  3 -4  0]
 [ 0 -6  1 -2 -5 -4  0  0  0  3]
 [ 7 -8  0  1  0 -1 -5  1  0  4]
 [ 1 -4 -3 -1  0  2  4 -5 -4  5]
 [-2  0  1  1  0 -2 -4 -3  1 -4]
 [ 2  0  4 -2  4  0 -4  0 -5  0]
 [-3 -1 -3  0 -1 -3 -1 -7 -1  0]
 [ 5  0 -2 -5  1  1 -1 -4 -4  2]
 [-1  2 -3  2 -2 -4 -4  1 -7  6]
 [ 1  0  3  0  0  3 -2 -2  0  0]]


# Day 10
## Maximin
### Función ```min```
* La función ```min``` devuelve el valor mínimo a lo largo de un eje dado.

```import numpy```

```my_array = numpy.array([[2, 5], ```

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;```[3, 7],```

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;```[1, 3],```

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;```[4, 0]])```


```print numpy.min(my_array, axis = 0)         #Output : [1 0]```

```print numpy.min(my_array, axis = 1)         #Output : [2 3 1 0]```

```print numpy.min(my_array, axis = None)      #Output : 0```

```print numpy.min(my_array)                   #Output : 0```

* Por defecto, el valor del eje es None. Por lo tanto, encuentra el mínimo en todas las dimensiones de la matriz de entrada.

### Función ```max```
* La función ```max``` devuelve el valor máximo a lo largo de un eje dado.

```import numpy```

```my_array = numpy.array([[2, 5], ```

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;```[3, 7],```

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;```[1, 3],```

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;```[4, 0]])```


```print numpy.max(my_array, axis = 0)         #Output : [4 7]```

```print numpy.max(my_array, axis = 1)         #Output : [5 7 3 4]```

```print numpy.max(my_array, axis = None)      #Output : 7```

```print numpy.max(my_array)                   #Output : 7```

* Por defecto, el valor del eje es None. Por lo tanto, encuentra el máximo en todas las dimensiones de la matriz de entrada.

### Objetivo
* Dada una matriz de orden nxm su tarea es calcular la función mínima sobre el eje 1 y luego encontrar el máximo de eso.

### Input
* La primera línea de entrada contiene los valores n y m separados por un espacio. Las siguientes n líneas contienen m conjuntos de enteros separados por espacios.

### Output
* Calcule el mínimo a lo largo del eje 1 y luego imprima el máximo de ese resultado.

### Ejemplo
#### Input
4 2  
2 5  
3 7  
1 3  
4 0

#### Output
3

#### Explicación
* El mínio a lo largo del eje 1 = [2,3,1,0]
* El máximo de [2,3,1,0] es 3.

## Nota
* Cree una función que genere aleatoriamente los inputs con diferentes dimensiones posibles.
* Cree una función que calcule el output.

# Day 11
## Capitalize
* Disponemos de una lista de nombres y una lista de apellidos
 - nombres = ['alba','alberto','alejandro','alicia','álvaro','ana','andrés','antonio','carla','carlos','carmen','cristina','daniel','david','eduardo','enrique','esther','eva','felipe','gabriel','hector','helena','hugo','isabel','iván','javier','jesus','jorge','juan','laura','lucas','lucía','luis','manuel','mar','margarita','maría','marta','martina','miguel','patricia','paula','pilar','raquel','raúl','rocío','samuel','sara','sonia','teresa']
 - apellidos = ['alonso','álvarez','blanco','cano','castillo','castro','cortes','delgado','diaz','dominguez','fernandez','garcía','garrido','gil','gomez','gonzalez','guerrero','gutierrez','hernandez','iglesias','jimenez','lopez','lozano','marin','martin','martinez','medina','mendez','molina','morales','moreno','muñoz','navarro','nuñez','ortega','ortiz','perez','ramirez','ramos','rodriguez','romero','rubio','ruiz','sanchez','santos','sanz','serrano','suarez','torres','vazquez']
* Crear una función que elige aleatoriamente un nombre y un apellido para formar con ellos el nombre y apellido de una persona, por ejemplo:
 - iván nuñez
 - raquel álvarez
* El programa devuelve el nombre y el apellido con la primera letra en mayúsculas del nombre y del apellido, por ejemplo:
 - Iván Nuñez
 - Raquel Álvarez
* Se ha de lograr sin utilizar la función ```title``` en Python que conseguiría el mismo resultado.
* * Se ha de lograr sin utilizar la función ```capitalize```

In [ ]:
n = "raquel álvarez"
print(n.title())

Raquel Álvarez


# Day 12
## Genética
* El ADN es una molécula formada por la combinación de las cuatro letras que son la base del código genético:
 - adenina (A)
 - timina (T)
 - citosina (C)
 - guanina (G)
* Por ejemplo:
  - AATCGCGCACCAATGCAATT
* Crear una función que genere combinaciones de estas cuatro letras de forma aleatoria.
 - A esta combinación la llamaremos **palabra**
 - Las palabras que genere nuestra función tendrán una longitud de 102 caracteres
 - Cada una de las letras aparecerá en términos de probabilidad con los siguientes porcentajes que son los del ADN humano:
  * A: 29,3%
  * G: 20,7%
  * C: 20%
  * T: 30%
* De la palabra generada obtendremos aleatoriamente una subcadena de 3 caracteres que llamaremos **secuencia**.
* Mostrar en pantalla la palabra
* Mostrar en pantalla todas las secuencias que se repitan más de una vez.
* Decir cuantas veces se encuentra contenida la secuencia dentro de la palabra (frecuencia)
* Ejemplo
 - La palabra debería ser de 102 caracteres, pero en el ejemplo usaremos una de 20 caracteres.  
 La palabra es 
 AATCGCGCACCAATGCAATT
 - Se mostrará en pantalla una tabla como la siguiente:  
 
| Secuencia | Frecuencia |
| :---: | :-: |
| AAT | 3 |
| CGC | 2 |
| GCA | 2 |
| CAA | 2 |

 - Comentario
  * La secuencia AAT está contenida en la palabra AATCGCGCACCAATGCAATT 3 veces.
  * La secuencia CGC está contenida en la palabra AATCGCGCACCAATGCAATT 2 veces.
  * Explicación de porque CGC está dos veces. Existe un tramo de la palabra que es CGCGC donde la secuencia buscada está dos veces.

* Nota  
Si una palabra no contiene ninguna secuencia con frecuencia mayor a 1, descartar la palabra y generar otra. Seguir generando palabras hasta que obtengamos alguna que contenga al menos una secuencia con frecuencia mayor a 1.

# Day 13
## Mutaciones
* Nos basamos en el reto anterior donde generamos palabras de 102 caracteres con las cuatro letras del alfabeto genético ACGT.
* Dada una palabra de 102 caracteres
 - Obtener todas las secuencias de 3 caracteres que tengan frecuencia mayor a 1
 - Realizar la **mutación**: alterar algun(os) caracter(es) de alguna(s) de las secuencias repetidas para conseguir que en la 'palabra mutada' no existan secuencias de 3 caracteres con repetición.
* Mostrar la palabra de 102 caracteres antes y después de haber realizado la mutación
* Ejemplo
 - La palabra debería ser de 102 caracteres, pero en el ejemplo usaremos una de 20 caracteres.
 - Palabra original: AATCGC**G**CACC**A**ATGCA**A**TT
 - Palabra  mutada:  AATCGC**T**CACC**C**ATGCA**G**TT
 - Registro binario: 00000010000100000100
* El 'registro binario' es una secuencia de ceros y unos, donde:
 - Si el caracter no ha cambiado se pone un 0
 - Si el caracter ha mutado se pone un 1
* El objetivo es eliminar todas las repeticiones de secuencias de 3 caracteres y conseguirlo procurando las mínimas alteraciones en la palabra original
* En el ejemplo la suma de los unos del registro binario es 3, lo que indica que únicamente se han alterado tres caracteres de la palabra original (tres mutaciones), y con ello hemos conseguido que desaparezcan todas las repeticiones en la secuencias de 3 caracteres.

# Day 14
## Separar elementos de una lista
* Generar una lista de 20 elementos con valores aleatorios donde en términos probables:
 - el 45% sean números
 - el 35% sean letras o símbolos
 - el 20% sean valores booleanos (True, False)
* Mostrar la lista generada en pantalla
* Separar la lista original en tres listas
 - una lista con los números
 - otra lista con las letras y símbolos
 - y finalmente otra lista con los valores booleanos

In [ ]:
# Separar elementos de una lista
import random
random.seed()
digitos = "0123456789"
letras_simbolos = "abcdefghijklmnñopqrstuvwxyzABCDEFGHIJKLMNÑOPQRSTUVWXYZºª\!|@#~€¬·$%&/()=?¿*+{}[].-:_><"
true_false = (True, False)  # tupla
lista = []
numeros = []
letras = []
booleanos = []

for i in range(20):
  rnd = random.random()
  if rnd < 0.45:
    lista.append(random.choice(digitos))
  elif rnd < 0.8:
    lista.append(random.choice(letras_simbolos))
  else:
    lista.append(random.choice(true_false))

print(f"Lista original:     {lista}")

for element in lista:
  if str(element) in digitos:
    numeros.append(element)
  elif str(element) in letras_simbolos:
    letras.append(str(element))
  else:
    booleanos.append(element)

print(f"Números:            {numeros}")
print(f"Letras y símbolos : {letras}")
print(f"Booleanos:          {booleanos}")

Lista original:     ['9', '2', 'K', False, 'H', '9', '1', '*', 'l', '5', '2', '6', 't', 'M', '+', True, 'S', '6', '0', True]
Números:            ['9', '2', '9', '1', '5', '2', '6', '6', '0']
Letras y símbolos : ['K', 'H', '*', 'l', 't', 'M', '+', 'S']
Booleanos:          [False, True, True]


# Day 15
### Numero total de combinaciones con 3 digitos donde num1<num2<num3
* Por ejemplo 123 467 serían combinaciones validas y 435 673 no
* Se debe dar el numero total de estas combinaciones

In [ ]:
# Numero total de combinaciones con 3 digitos donde num1<num2<num3
digitos = "0123456789"
n = 0    # contador

for p in digitos:
  for q in digitos:
    for r in digitos:
      if p<q<r:
        salto = ""
        if not((n+1)%10): salto='\n'      # salto de línea cada 10 números 
        print(f"{p+q+r} {salto}", end="")
        n += 1

print(f"\nExisten {n} combinaciones.")

012 013 014 015 016 017 018 019 023 024 
025 026 027 028 029 034 035 036 037 038 
039 045 046 047 048 049 056 057 058 059 
067 068 069 078 079 089 123 124 125 126 
127 128 129 134 135 136 137 138 139 145 
146 147 148 149 156 157 158 159 167 168 
169 178 179 189 234 235 236 237 238 239 
245 246 247 248 249 256 257 258 259 267 
268 269 278 279 289 345 346 347 348 349 
356 357 358 359 367 368 369 378 379 389 
456 457 458 459 467 468 469 478 479 489 
567 568 569 578 579 589 678 679 689 789 

Existen 120 combinaciones.


# Day 16
## Comprobador de letras repetidas
* Crear una función que recoge un parámetro string
* La función debe retornar cuantas veces aparecen las palabras repetidas

Ejemplo:

String = "yes yes bye good okay bye okay bye"

Output = "yes" 2, "okay" 2, "bye" 3 

In [ ]:
# Comprobador de letras repetidas
frase = "Un hombre sólo tiene derecho a mirar a otro hacia abajo, cuando ha de ayudarle a levantarse."  # Gabriel García Márquez

def depura(frase):                 # depuramos la frase eliminando signos de puntuación y acentos
  frase = frase.replace(',', '')
  frase = frase.replace('.', '')
  frase = frase.replace('á', 'a')
  frase = frase.replace('é', 'e')
  frase = frase.replace('í', 'i')
  frase = frase.replace('ó', 'o')
  frase = frase.replace('ú', 'u')
  return frase

def caracteres_repetidos(frase):
  palabras = []    # lista de palabras con caracteres repetidos
  todas = frase.split(' ')
  for palabra in todas:
    repe = False                     # bandera
    for caracter in palabra:
      if palabra.count(caracter)>1:
        repe = True
    if repe:
      palabras.append(palabra)
  return palabras

con_repetidos = caracteres_repetidos(depura(frase))
print(con_repetidos)
print(f"La frase inicial tiene {len(frase.split(' '))} palabras y de ellas tienen caracteres repetidos {len(con_repetidos)} palabras.")

['solo', 'tiene', 'derecho', 'mirar', 'otro', 'hacia', 'abajo', 'ayudarle', 'levantarse']
La frase inicial tiene 17 palabras y de ellas tienen caracteres repetidos 9 palabras.


# Day 17
## Aplicación con JSON
* Crear menú para interactuar con un JSON
* Ver la información que contiene el JSON
* Poder añadir información
    * Nuevos alumnos
    * Nuevas notas
* Poder editar información ya existente
* Poder eliminar información
* Calcular la nota media automáticamente

JSON de ejemplo:
```json
{
	"Maria": {
		"average": null,
		"grades": [1.0, 2.5, 5.3, 2.7]
	},
	"Alberto": {
		"average": null,
		"grades": [9.2, 4.2, 7.9, 1.4]
	},
	"Victor": {
		"average": null,
		"grades": [9.6, 9.7, 5.1, 7.5]
	},
	"Tania": {
		"average": null,
		"grades": [7.4, 6.1, 1.2, 3.9]
	}
}

```

# Day 18
## Juego de la ultima piedra
* Generar un numero aleatorio de piedras. (15-30 por ejemplo)
* Hay dos jugadores, en cada turno pueden elegir quitar 1, 2 o 3 piedras, siempre hay que quitar piedras
* El jugador que quite la ultima piedra pierde
* Uno de los jugadores es la maquina

# Day 19
## Calcular el determinante
* Generar una matriz cuadrada de nº aleatorios de orden n, como en el reto 9, sin que exista una fila o columna con todos los nº = cero
* n puede ir de 1 a 100
* Crear una función que calcule el determinante (por método de Gauss, haciendo ceros, construyendo una matriz triangular)
* Comprobara el resultado con el determinante obtenido con NumPy 
* Generar matrices hasta encontrar una cuyo determinante sea cero

In [ ]:
import numpy as np
from random import random, seed
from copy import deepcopy
np.random.seed()
seed()

def matriz(n):  # genera una matriz de orden n con elementos entre -9 y +9 con cierta probabilidad
  while True:
    m = [[-x if random()<.5 else x for x in np.random.choice(10, n, p=[.25,.20,.16,.12,.09,.07,.05,.03,.02,.01])] for _ in range(n)]
    m = np.asarray(m, dtype=float)   # convertimos la matriz en un ndarray, con números que pueden ser float
    if np.where(~m.any(axis=0))[0].size == 0 and np.where(~m.any(axis=1))[0].size == 0:  # no puede tener alguna fila o columna con todos ceros
      break
  return m

def determinante(m):
  n = len(m[0])
  d = 1  # el determinante se inicializa en 1
  while n>1:
    if abs(m[0][0])<1e-12:  # si pongo m[0][0]==0 se salta los valores muy muy cercanos a cero pero no cero
      for i in range(1,n):
        if abs(m[i][0]) >= 1e-12:    # si pongo m[i][0] != 0 da problemas con valores muy muy cercanos a cero pero no cero
          m[0], m[i] = deepcopy(m[i]), deepcopy(m[0]) # permuta filas
          d *= -1  # al permutar dos filas el determinante cambia de signo
          break      
    for i in range(1,n): # analizando los elementos de la primera columna del index 1 al n
      if abs(m[i][0]) >= 1e-12:  # si el primer elemento de una fila es distinto de cero
        factor = -m[i][0]/m[0][0]
        for j in range(n):
          m[i][j] += factor * m[0][j] # El determinante no cambia si se suma a una fila otra fila multiplicada por un factor
    d *= m[0][0]
    m = deepcopy(m[1:n, 1:n]) # reducimos el tamaño de la matriz eliminando la primera fila y la primera columna
    n = len(m[0])
  else:
    d *= m[0][0]
  return d

while True:
  m = matriz(6)
  c = deepcopy(m)  # copia de la matriz original
  d = determinante(m)
  if abs(d) < 1e-6:
    print("Determinante con Numpy:", np.linalg.det(c))
    print("Determinante con algoritmo:", d)
    print("\n", c)
    break

Determinante con Numpy: 0.0
Determinante con algoritmo: 0.0

 [[ 0.  8.  0.  0.  0. -7.]
 [ 0. -1. -4.  2.  0. -5.]
 [ 1.  2.  5. -2.  0. -4.]
 [ 2.  0.  0.  5. -4.  4.]
 [-1.  0.  3. -2.  0.  3.]
 [ 0. -5.  0.  2. -2.  0.]]


# Day 20
## Histograma de la distribución de Poisson
* Generar un array con la distrubución de [Poisson](https://en.wikipedia.org/wiki/Poisson_distribution)
* El array debe contener un gran numero de elementos, por ejemplo un millón
* Probar con diferentes medias (lambda)
* Mostrar un grafico con el histograma de frecuencias

# Day 21
## Canguros saltando
* Disponemos de dos canguros en un circo que saltan en una pista lineal numerada.
* Siempre saltan hacia la derecha, hacia valores positivos, cada vez mayores en la recta
* El canguro 1 parte del punto $x_1$ y se mueve con velocidad $v_1$
* El canguro 2 parte del punto $x_2$ y se mueve con velocidad $v_2$
* Se trata de ver si los dos canguros estén en el mismo lugar al mismo tiempo como parte del espectáculo.
* Crearemos la función kangaroo donde si no es posible que los canguros coincidan, devuelve NO, de lo contrario devuelve en que posición $x$ coinciden.
* Ejemplo
 - $x_1=2$
 - $v_1=1$
 - $x_2=1$
 - $v_2=2$
 - Después de un salto, ambos están en $x=3$, por lo que la respuesta es 1.
 - Sabemos que coinciden en $x=3$ ya que:
   * $x_1 + v_1 = 2 + 1 = 3$
   * $x_2 + v_2 = 1 + 2 = 3$
* La función kangaroo recibe un único parámetro que es un string con cuatro números separados por un espacio. Los números son $x_1 \; v_1 \; x_2 \; v_2$ en ese orden.
* Crear otra función que genere el string con los cuatro valores anteriores para podérselos pasar a la función kangaroo
* Rangos de variación
 - $0 \leq x_1 < x_2 \leq 10000$
 - $1 \leq v_1 \leq 10000$
 - $1 \leq v_2 \leq 10000$
 - todos son valores enteros

#### Ejemplo
* Los valores de entrada de la función kangaroo, en forma de un string, son
 - 0 3 4 2

<img src="https://github.com/seldoncode/AdventOfCode2021/blob/main/kangaroo.png?raw=1" alt="Banana.png" width="600"/>

* De la imagen, está claro que los canguros se encuentran en el mismo lugar (número en la recta numérica) después de la misma cantidad de saltos (4 saltos), e imprimimos 4.

#### Ejemplo
* Los valores de entrada de la función kangaroo, en forma de un string, son
 - 0 2 5 3
* El segundo canguro tiene una ubicación de inicio que está adelante (más a la derecha) de la ubicación de inicio del primer canguro (es decir, $x_2 > x_1$). Debido a que el segundo canguro se mueve a un ritmo más rápido (es decir, $v_2 > v_1$) y ya está por delante del primer canguro, el primer canguro nunca podrá alcanzarlo. Por lo tanto, imprimimos NO.

### Función genera
* La función genera crea un string con los cuatro valores $x_1 \; v_1 \; x_2 \; v_2$ en ese orden.
* Cada uno de esos valores se puede obtener de una distribución de Poisson o distribución de los grandes números.
* Como esta distribución comienza en 0 es ideal para $x_1$ y para $x_2$. En el caso de $v_1$ y para $v_2$ como comienzan en 1, se puede lograr sumando 1 al número aleatorio obtenido de la Poisson.
* La distribución de Poisson es una distribución de un solo parámetro que es su media. Obtener esa media usando un número aleatorio entero y pequeño.
 - Por ejemplo medias que van entre 2 y 9, pueden estar bien.

# Day 22
## Calcular la matriz inversa
* Dada una matriz cuadrada de orden _n_ calcular la matriz inversa
* _n_ puede variar entre 1 y 100
* Resolver por tres metodos:
    * Con NumPy
    * Por Gauss (haciendo ceros)
    * Desarollando por el menor complementario

# Day 23
## Resolver un sistema de ecuaciones de solución única
* El sistema de ecuaciones tiene el mismo numero de incógnitas que de ecuaciones (_n_)
* El determinante de la matriz de coeficientes es distinto de 0 para que tenga solución única

# Day 24
## Calcular la TIR de una inversión
* Dada una inversión con una serie de flujos de caja anuales, calcular la TIR ([IRR](https://en.wikipedia.org/wiki/Internal_rate_of_return) en inglés) por varios métodos:
 - Usando alguna librería
 - Crear una función que calcula la TIR por aproximaciones sucesivas, usando cálculo numérico
* Crear una función que genera una inversión con posible flujos de caja para luego poder pasar estos flujos de caja a la otra función y obtener la TIR
* Ejemplo
 - La TIR de la siguiente operación de inversión es del 10% anual.

| Años | Flujos de caja |
| :---: | :-: |
| 0 | -4.000 |
| 1 | 1.400 |
| 2 | 1.300 |
| 3 | 1.200 |
| 4 | 1.100 |

# Day 25
## Óptimos de Pareto
* Generar $n$ parejas de números aleatorios $(x,y)$, donde cada pareja representa un punto del plano
 - $n$ pueden ser por ejemplo 50 parejas
 - x e y pueden ser números aleatorios con decimales, entre 0 y 1
* Considerar que la coordenada x representa la producción del bien A
* Considerar que la coordenada y representa la producción del bien B
* Generar diferentes conjuntos de $n$ puntos aleatorios hasta llegar a obtener un caso donde de ellos $m$ puntos sean óptimos de Pareto
 - donde $m<n$
 - siendo $m$, por ejemplo, 16 puntos del plano
* El óptimo de pareto se alcanza maximizando la producción de los bienes A y B
* Representar los $n$ puntos en el plano, diferenciando con otro color los $m$ puntos óptios de Pareto.

<img src="https://github.com/seldoncode/AdventOfCode2021/blob/main/pareto16.png?raw=1" alt="pareto.png" width="480"/>